version: 0.2

phases:
  pre_build:
    commands:
      echo Running Pre-Build
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      echo docker login successfull
  build: 
    commands:
      echo trying build....
      docker build . -t ypavankumar123/nodeappcontainer
      echo docker build successfull
  post_build:
    commands:
      echo pushing image
      docker image tag ypavankumar123/nodeappcontainer:latest ypavankumar123/nodeappcontainer:${CODEBUILD_BUILD_NUMBER}
      docker image push ypavankumar123/nodeappcontainer:${CODEBUILD_BUILD_NUMBER}
      echo image pushed123...
